IF OBJECT_ID('tempdb..#TEMP') IS NOT NULL
DROP TABLE #TEMP
CREATE TABLE #TEMP (ID INT, NAME VARCHAR(10))
 
INSERT INTO #TEMP (ID, NAME)
VALUES (1,'April'), (1,'Ron'), (2,'Hellen'), (2,'John'), (2,'Bill')
 
--XML
SELECT ID,
(SELECT (NAME +', ' )
FROM #TEMP T1
WHERE T1.ID = T2.ID
FOR XML PATH('')) AS NAMES
From #TEMP T2
GROUP BY ID
 
--CROSS APPLY
SELECT DISTINCT ID, D.NAME
FROM #TEMP AS T2
CROSS APPLY (SELECT (NAME +', ' )
FROM #TEMP T1
WHERE T1.ID = T2.ID
FOR XML PATH('')) D (NAME)